background_image: "hidden_king.jpg"
timezone: "Europe/Berlin"

sections:
  - clock
  - bookmarks
  - forecast
  - media

bookmarks:
  - name: "Dev"
    links:
      - title: "Github"
        url: "https://github.com"
      - title: "Gitlab"
        url: "https://gitlab.com/"
  - name: "Ai"
    links:
      - title: "Claude"
        url: "https://claude.ai/"
      - title: "Gemini"
        url: "https://gemini.google.com/app"
  - name: "Google"
    links:
      - title: "Gmail"
        url: "https://mail.google.com"
      - title: "Google Calendar"
        url: "https://calendar.google.com"
  - name: "Listen"
    links:
      - title: "Audible"
        url: "https://www.audible.co.uk"
      - title: "Spotify"
        url: "https://open.spotify.com"
  - name: "Other"
    links:
      - title: "Allegro"
        url: "https://allegro.pl/"
      - title: "Cronometer"
        url: "https://cronometer.com/"
